const vebinarsData = [
  {
    title: "Бизнес Amway - новая digital реальность",
    date: "26&nbsp;июня",
    author: "Юлия Юдина, менеджер по продвижению цифровых продуктов и управлению изменениями; Иван Адамидис, Платиновый Лидер-основатель бизнеса (Казахстан) и Елизавета Экштат, Независимый Предприниматель Amway 9% уровень, Россия",
    image: "./images/vebinars/leader-34.png",
    link: "https://youtu.be/jKjZYcTMVFE",
    document: "./documents/doc.pdf",
  },
  {
    title: "Ирина Меньшикова и&nbsp;Александр Калинин в&nbsp;гостях у&nbsp;#ДОМАСAMWAY",
    date: "19&nbsp;июня",
    author: "Ирина Меньшикова, Управляющий Директор Amway Россия и Казахстан и Александр Калинин, Президент Общероссийской общественной организации малого и среднего предпринимательства «ОПОРА РОССИИ»",
    image: "./images/vebinars/leader-33.png",
    link: "https://youtu.be/hO9ka79TfYI",
    document: "./documents/doc.pdf",
  },
  {
    title: "Как стать экспертом в области красоты и здоровья в соцсетях",
    date: "12&nbsp;июня",
    author: "Галина Оноприенко, digital-эксперт, маркетинговое агентство Fibonacci",
    image: "./images/vebinars/leader-32.png",
    link: "https://youtu.be/mc_5aGZygcQ",
    document: "./documents/doc.pdf",
  },
  {
    title: "Значение витаминов и&nbsp;минералов в&nbsp;рационе детей",
    date: "5&nbsp;июня",
    author: "Cергей Чудаков, кандидат медицинских наук, эксперт бренда Nutrilite",
    image: "./images/vebinars/leader-31.png",
    link: "https://youtu.be/YOsCVp_U0wo",
    document: "./documents/doc.pdf",
  },
  {
    title: "Социальные сети в&nbsp;бизнесе Amway",
    date: "29&nbsp;мая",
    author: "Ушакова Виктория, ведущий специалист по&nbsp;дистанционному обучению; Тыщенко Елена, Платиновый Лидер Amway, эксперт в&nbsp;Digital Lab; Капанова Динара Платиновый Лидер Amway, победить конкурса Passionista",
    image: "./images/vebinars/leader-30.png",
    link: "https://youtu.be/5EsAaZhKn7s",
    document: "./documents/doc.pdf",
  },
  {
    title: "Зарабатывай дома онлайн",
    date: "27&nbsp;мая",
    author: "Анжелика Шатулина-Измайлова, Сапфировый Лидер-основатель бизнеса; Борис Экштат, Бриллиантовый Лидер-администратор",
    image: "./images/vebinars/leader-29.png",
    link: "https://youtu.be/aaDhHDkmqVU",
    document: "./documents/doc.pdf",
  },
  {
    title: "Форма глаз и&nbsp;их коррекция при&nbsp;помощи макияжа",
    date: "25&nbsp;мая",
    author: "Анна Синица, федеральный эксперт, визажист Artistry",
    image: "./images/vebinars/leader-28.png",
    link: "https://youtu.be/PlB_6fVfD6M",
    document: "./documents/doc.pdf",
  },
  {
    title: "Домашний уход с&nbsp;Artistry Dermasonic",
    date: "22&nbsp;мая",
    author: "Александра Гонт, врач дерматолог-косметолог, эксперт бренда Artistry",
    image: "./images/vebinars/leader-27.png",
    link: "https://youtu.be/XoMLrllJJHg",
    document: "./documents/doc.pdf",
  },
  {
    title: "Милинд Пант и&nbsp;Ирина Меньшикова в&nbsp;гостях у&nbsp;#ДОМАСAMWAY",
    date: "20&nbsp;мая",
    author: "Милинд Пант, Генеральный директор Amway и&nbsp;Ирина Меньшикова, Управляющий директор Amway Россия и&nbsp;Казахстан",
    image: "./images/vebinars/leader-26.png",
    link: "https://youtu.be/cNT9rUsJ2Qw",
    document: "./documents/doc.pdf",
  },
  {
    title: "Основной уход и&nbsp;восстановление волос",
    date: "18&nbsp;мая",
    author: "Юлия Фортуна, эксперт по&nbsp;уходу за&nbsp;волосами",
    image: "./images/vebinars/leader-25.png",
    link: "https://youtu.be/eMdvQRdSAds",
    document: "./documents/doc.pdf",
  },
  {
    title: "Социальные cети: обзор, тренды, UGC-контент от&nbsp;партнеров",
    date: "15&nbsp;мая",
    author: "Анастасия Архипова, Менеджер по&nbsp;интернет-коммуникациям Amway и&nbsp;Денис Шолохов, эксперт по&nbsp;SMM, агентство WaveMaker",
    image: "./images/vebinars/leader-24.png",
    link: "https://youtu.be/-LTlQO12HMY",
    document: "./documents/doc.pdf",
  },
]